import type { Doc } from "../_generated/dataModel";

/**
 * Single default title used for every newly created thread, regardless of mode
 * (Discuss / Library / Library Ask) or whether the thread is bound to a
 * repository. Repo / mode signals already surface in other sidebar columns
 * (badges, mode rail filter), so the title field is freed up for either the
 * autogenerated summary written by `generateThreadTitle` or a manual rename
 * via `renameThread`.
 *
 * Keeping the literal in one place lets the title-autogen path's race guard
 * (`isDefaultTitle`) stay a single string-equality check — see `titles.ts`
 * for the patch-time guard that refuses to overwrite a user-renamed thread.
 */
export const NEW_THREAD_DEFAULT_TITLE = "New chat";

/**
 * Cap on manual-rename thread title length. Lives here (not in
 * `chat/threads.ts`) so the rail's inline-rename `<input>` can mirror the
 * cap in `maxLength` without dragging the server-side mutation module
 * into the client bundle.
 *
 * Intentionally larger than `MAX_AUTOGEN_TITLE_LENGTH` (80, in
 * `titleSanitization.ts`) — manual renames trust the user, autogen does
 * not trust the model.
 */
export const MAX_RENAME_TITLE_LENGTH = 200;

/**
 * Whether a thread still carries the default title — i.e. neither the user
 * nor the autogen pass has replaced it. Used as a race guard before the
 * `generateThreadTitle` action's patch so a mid-flight rename by the user
 * always wins over the late-arriving LLM summary.
 */
export function isDefaultTitle(thread: Doc<"threads">): boolean {
  return !thread.userEditedTitle && thread.title === NEW_THREAD_DEFAULT_TITLE;
}
