import { useState } from "react";
import { useMutation, useQuery } from "convex/react";
import { FileTextIcon, SparkleIcon } from "@phosphor-icons/react";
import { api } from "../../convex/_generated/api";
import { Alert, AlertDescription } from "@/components/ui/alert";
import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Spinner } from "@/components/ui/spinner";
import { useAsyncCallback } from "@/hooks/use-async-callback";
import { toUserErrorMessage } from "@/lib/errors";
import type { RepositoryId } from "@/lib/types";

/**
 * The checklist the Generate System Design dialog renders. Order and labels
 * are deliberately hardcoded here so the dialog matches the publication
 * narrative even if the backend catalog grows additional kinds — new kinds
 * will appear as an "unrendered" warning instead of silently changing the UI
 * vocabulary. Every kind is LLM-backed: the generator opens a sandbox and
 * inspects live source, so there is no free / paid split. Order mirrors the
 * seeded System Design folder tree.
 */
const CATALOG: ReadonlyArray<{
  kind:
    | "readme_summary"
    | "architecture_overview"
    | "architecture_diagram"
    | "data_model_overview"
    | "api_surface_overview"
    | "deployment_overview"
    | "security_overview"
    | "operations_overview";
  title: string;
  description: string;
}> = [
  {
    kind: "readme_summary",
    title: "README Summary",
    description: "Purpose, services, audience, and key operations distilled from the README.",
  },
  {
    kind: "architecture_overview",
    title: "Architecture Overview",
    description: "Components, responsibilities, data and control flow, and key boundaries.",
  },
  {
    kind: "architecture_diagram",
    title: "Architecture Diagram",
    description: "Mermaid graph of components, flows, and boundaries — with legend and reading guide.",
  },
  {
    kind: "data_model_overview",
    title: "Data Model Overview",
    description: "Persistent stores, entities, relationships, invariants.",
  },
  {
    kind: "api_surface_overview",
    title: "API Surface Overview",
    description: "Externally-visible endpoints, auth, request/response shapes.",
  },
  {
    kind: "deployment_overview",
    title: "Deployment Overview",
    description: "Runtime targets, build pipeline, infra dependencies.",
  },
  {
    kind: "security_overview",
    title: "Security Overview",
    description: "Auth, authorisation, input validation, sensitive data.",
  },
  {
    kind: "operations_overview",
    title: "Operations Overview",
    description: "Logging, metrics, tracing, alerting, run-books.",
  },
];

type Kind = (typeof CATALOG)[number]["kind"];

export function GenerateSystemDesignDialog({
  open,
  onOpenChange,
  repositoryId,
}: {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  repositoryId: RepositoryId;
}) {
  const activeJob = useQuery(api.systemDesign.getActiveSystemDesignJob, { repositoryId });
  const requestGeneration = useMutation(api.systemDesign.requestSystemDesignGeneration);

  // Every document is worth generating, so the publication defaults to the
  // full set — the user unticks what they don't want rather than opting in.
  const [selected, setSelected] = useState<Set<Kind>>(() => new Set(CATALOG.map((item) => item.kind)));
  const [error, setError] = useState<string | null>(null);
  const [previousOpen, setPreviousOpen] = useState(open);
  if (previousOpen !== open) {
    setPreviousOpen(open);
    setError(null);
  }

  const toggle = (kind: Kind) => {
    setSelected((prev) => {
      const next = new Set(prev);
      if (next.has(kind)) next.delete(kind);
      else next.add(kind);
      return next;
    });
  };

  const [isSubmitting, runSubmit] = useAsyncCallback(async () => {
    setError(null);
    const selections = Array.from(selected);
    if (selections.length === 0) {
      setError("Select at least one document to generate.");
      return;
    }
    try {
      await requestGeneration({ repositoryId, selections });
      onOpenChange(false);
    } catch (err) {
      setError(toUserErrorMessage(err, "Failed to start generation."));
    }
  });

  const jobInProgress = activeJob != null;

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-lg">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <SparkleIcon size={16} weight="bold" />
            Generate System Design
          </DialogTitle>
          <DialogDescription>
            Choose which documents to include in this publication. Each one is generated by inspecting your repository's
            live source in the sandbox (~1 LLM call each).
          </DialogDescription>
        </DialogHeader>

        {jobInProgress ? (
          <Alert>
            <AlertDescription className="text-[12px]">
              A generation is already in progress for this repository. Close this dialog and watch the folder navigator
              — new artifacts will appear as each kind completes.
            </AlertDescription>
          </Alert>
        ) : null}

        <ul className="flex max-h-[60vh] flex-col gap-1 overflow-y-auto py-1">
          {CATALOG.map((item) => {
            const checked = selected.has(item.kind);
            return (
              <li key={item.kind}>
                <label
                  className="flex cursor-pointer items-start gap-3 p-2 transition hover:bg-muted"
                  htmlFor={`gen-${item.kind}`}
                >
                  <input
                    id={`gen-${item.kind}`}
                    type="checkbox"
                    className="mt-1 h-4 w-4 accent-primary"
                    checked={checked}
                    onChange={() => toggle(item.kind)}
                    disabled={isSubmitting || jobInProgress}
                  />
                  <div className="flex flex-1 flex-col gap-0.5">
                    <div className="flex items-center gap-2">
                      <FileTextIcon size={12} weight="bold" className="text-muted-foreground" />
                      <span className="text-[13px] font-medium">{item.title}</span>
                    </div>
                    <p className="text-[11px] leading-snug text-muted-foreground">{item.description}</p>
                  </div>
                </label>
              </li>
            );
          })}
        </ul>

        {error ? (
          <Alert variant="destructive">
            <AlertDescription className="text-[12px]">{error}</AlertDescription>
          </Alert>
        ) : null}

        <DialogFooter className="flex-col gap-2 sm:flex-row sm:items-center sm:justify-between">
          <div className="text-[11px] text-muted-foreground">
            Selected: <strong>{selected.size}</strong> of {CATALOG.length} documents.
          </div>
          <div className="flex gap-2">
            <Button
              type="button"
              variant="outline"
              size="sm"
              onClick={() => onOpenChange(false)}
              disabled={isSubmitting}
            >
              Cancel
            </Button>
            <Button
              type="button"
              size="sm"
              onClick={() => void runSubmit()}
              disabled={isSubmitting || jobInProgress || selected.size === 0}
            >
              {isSubmitting ? (
                <>
                  <Spinner size={14} className="mr-2" />
                  Starting…
                </>
              ) : (
                "Generate selected"
              )}
            </Button>
          </div>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
